version: '3'
services:
  #POST_SERVER (API SERVER)
  api:
    image: python:3.9
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    command: bash -c "pip install -r requirements.txt && python post_server.py"
    depends_on:
      - db
    networks:
      - mynetwork
  #MYSQL DB
  db:
    image: mysql/mysql-server
    environment:
      MYSQL_DATABASE: DB
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - mynetwork

  #WEB DJANGO
  web:
    image: python:3.9
    working_dir: /appweb
    volumes:
      - .:/appweb
    ports:
      - "8000:8000"
    command: bash -c "python .\manage.py runserver"
    depends_on:
      - db
    networks:
      - mynetwork
    

networks:
  mynetwork:
  