# Generated by Django 3.2.6 on 2023-06-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('number', models.IntegerField()),
                ('nationality', models.CharField(max_length=250)),
                ('dob', models.DateField()),
                ('comments', models.TextField()),
            ],
        ),
    ]
